=== kurtizone/studying/xerces-parsing/src/main/resources/cars.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema targetNamespace="http://www.w3schools.com/Kurtizone"
	elementFormDefault="qualified" xmlns="http://www.w3schools.com/Kurtizone cars.xsd"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="cars">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="car" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="manufacturer" type="xs:normalizedString" />
							<xs:element name="model" type="xs:normalizedString" />
							<xs:element name="weight" type="xs:integer" />
							<xs:element name="maxSpeed" type="xs:integer" />
							<xs:element name="color" type="xs:normalizedString" />
							<xs:element name="price" type="xs:integer" />
						</xs:sequence>
						<xs:attribute name="id" type="xs:normalizedString" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>


</xs:schema>

=== kurtizone/studying/xerces-parsing/target/classes/cars.xml
<?xml version="1.0" encoding="UTF-8"?>
<cars xmlns="http://www.w3schools.com/Kurtizone" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3schools.com/Kurtizone cars.xsd"
	xsi:noNamespaceSchemaLocation="cars.xsd">
	<car id="1">
		<manufacturer>Mitsubishi</manufacturer>
		<model>Lancer</model>
		<weight>2100</weight>
		<maxSpeed>180</maxSpeed>
		<color>red</color>
		<price>14000</price>
	</car>
	<car id="2">
		<manufacturer>Volkswagen</manufacturer>
		<model>Golf</model>
		<weight>1600</weight>
		<maxSpeed>160</maxSpeed>
		<color>gray</color>
		<price>6000</price>
	</car>
	<car id="3">
		<manufacturer>Mercedes</manufacturer>
		<model>AMG</model>
		<weight>1950</weight>
		<maxSpeed>240</maxSpeed>
		<color>black</color>
		<price>60000</price>
	</car>
	<car id="4">
		<manufacturer>Mazda</manufacturer>
		<model>MX-5</model>
		<weight>1500</weight>
		<maxSpeed>200</maxSpeed>
		<color>red</color>
		<price>10500</price>
	</car>


</cars>
